#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Rebuild the social-jetlag example logs and pin every sample report.

Two residents of the same three weeks (2026-08-17 .. 2026-09-06, 15 work
nights / 6 free nights), two opposite diagnoses:

  * mia  — the owl: alarm days end at 07:10, free days drift to 10:40.
    Social jetlag +2h50m (HIGH), weekend repays only 32% of the debt.
    One Wednesday she sleeps in to 08:10 (doctor visit, alarm still set)
    and three Fridays run late — noise the medians must survive.
  * lee  — the lark: lights out at 22:40, awake before the birds.
    Social jetlag +0h15m (ALIGNED) — yet still 43h of debt per year.

Run `python3 examples/build_examples.py` to (re)generate `wooly-week.tsv`,
`lark-week.tsv` and the four pinned sample reports.
Run with `--check` to verify the committed files still match a fresh
rebuild byte for byte (used by the acceptance suite).
"""

from __future__ import annotations

import argparse
import io
import os
import sys
from contextlib import redirect_stdout
from datetime import date, timedelta

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)                 # social-jetlag/

sys.path.insert(0, ROOT)
import social_jetlag as sjl  # noqa: E402

FIRST = date(2026, 8, 17)                    # a Monday
DAYS = 21                                    # 15 work / 6 free

HEADER = "# generated by examples/build_examples.py — do not edit by hand\n" \
         "date\tsleep\twake\tkind\talarm\n"


def mia_rows():
    """Owl schedule with realistic noise: late Fridays, one late Wednesday."""
    rows = []
    for i in range(DAYS):
        day = FIRST + timedelta(days=i)
        if day.weekday() < 5:
            if day.weekday() == 4:                    # Friday, week drifts
                s, w, a = "01:20", "07:10", "yes"
            elif day == date(2026, 8, 26):            # doctor visit, alarm set
                s, w, a = "00:50", "08:10", "yes"
            else:
                s, w, a = "00:20", "07:10", "yes"
            rows.append("%s\t%s\t%s\twork\t%s" % (day, s, w, a))
        else:
            if day == date(2026, 9, 5):               # Saturday out
                s, w, a = "03:10", "11:20", "no"
            elif day == date(2026, 9, 6):             # Sunday, early plans
                s, w, a = "01:40", "09:00", "no"
            else:
                s, w, a = "02:30", "10:40", "no"
            rows.append("%s\t%s\t%s\tfree\t%s" % (day, s, w, a))
    return rows


def lee_rows():
    """Lark schedule, metronome-steady: the aligned control."""
    rows = []
    for i in range(DAYS):
        day = FIRST + timedelta(days=i)
        if day.weekday() < 5:
            rows.append("%s\t22:40\t05:50\twork\tyes" % day)
        else:
            rows.append("%s\t22:50\t06:10\tfree\tno" % day)
    return rows


def sample_files():
    return {
        "wooly-week.tsv": HEADER + "\n".join(mia_rows()) + "\n",
        "lark-week.tsv": HEADER + "\n".join(lee_rows()) + "\n",
    }


def sample_reports():
    """The four pinned reports, produced by the real CLI code paths.
    Runs with CWD=examples so the pinned path in each report is the bare
    file name — stable across machines."""
    out = {}
    cwd = os.getcwd()
    os.chdir(HERE)
    try:
        def capture(fn, *a, **kw):
            buf = io.StringIO()
            with redirect_stdout(buf):
                code = fn(*a, **kw)
            assert code == sjl.EXIT_OK, (fn, code)
            return buf.getvalue()

        out["sample-report-mia.txt"] = capture(
            sjl.main, ["report", "wooly-week.tsv"])
        out["sample-report-lark.txt"] = capture(
            sjl.main, ["report", "lark-week.tsv"])
        out["sample-simulate-flat.txt"] = capture(
            sjl.main, ["simulate", "wooly-week.tsv", "flat"])
        out["sample-simulate-target.txt"] = capture(
            sjl.main, ["simulate", "wooly-week.tsv", "target", "60"])
    finally:
        os.chdir(cwd)
    return out


def rebuild() -> dict:
    files = sample_files()
    write_all(files)          # TSVs on disk first: the reports read them back
    files.update(sample_reports())
    return files


def write_all(files: dict) -> None:
    for name, content in files.items():
        with open(os.path.join(HERE, name), "w", encoding="utf-8") as fh:
            fh.write(content)


def read_one(name: str) -> str:
    with open(os.path.join(HERE, name), "r", encoding="utf-8") as fh:
        return fh.read()


def check() -> int:
    bad = []
    # verify the logs first (no side effects), then regenerate them so the
    # pinned reports can be produced and compared too.
    for name, content in sorted(sample_files().items()):
        if read_one(name) != content:
            bad.append(name)
    if not bad:
        write_all(sample_files())
        for name, content in sorted(sample_reports().items()):
            if read_one(name) != content:
                bad.append(name)
    total = len(sample_files()) + len(sample_reports())
    if bad:
        print("out of sync: %s" % ", ".join(bad))
        print("run: python3 examples/build_examples.py")
        return 1
    print("all %d example files in sync" % total)
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="verify committed files match a fresh rebuild")
    args = ap.parse_args()
    if args.check:
        return check()
    files = rebuild()
    write_all(files)          # reports were only captured in memory so far
    print("wrote %d files:" % len(files))
    for name in sorted(files):
        print("  %s" % name)
    return 0


if __name__ == "__main__":
    sys.exit(main())
