#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Rebuild the ghost-login example vaults and pin every sample output.

Two vaults, two opposite diagnoses (both "as of" their own last date —
the clock is part of the vault, never the wall):

  * zhou — eleven years online, twelve accounts, never once cleaned:
    3 ZOMBIE (CloudDrive 76 — a *vital* account, password never rotated
    since 2016, never re-logged; NewsSite 65; OldForum 63), 5 MUSTY,
    4 SOUND. Three password clusters, and the primary inbox
    zhou@mail.com is the username — the recovery channel — for two of
    the zombies. StreamVideo still runs "12345678".
  * mei — the control: three accounts, unique passwords, one of them
    rotated last year. Everything SOUND, no clusters, nothing due.

Run `python3 examples/build_examples.py` to (re)generate `zhou-vault.tsv`,
`mei-vault.tsv` and the four pinned sample outputs.
Run with `--check` to verify the committed files still match a fresh
rebuild byte for byte (used by the acceptance suite).
"""

from __future__ import annotations

import argparse
import io
import os
import sys
from contextlib import redirect_stdout

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)                 # ghost-login/

sys.path.insert(0, ROOT)
import ghost_login as gl  # noqa: E402

HEADER = "# generated by examples/build_examples.py — do not edit by hand\n" \
         "name\tusername\tpassword\tpw_set\tlast_used\ttier\n"

# (name, username, password, pw_set, last_used, tier); "-" = never re-logged
ZHOU_ROWS = [
    ("OldForum", "zhou@mail.com", "hunter22", "2011-03-01", "-", "normal"),
    ("MusicSite", "zhou85@qq.com", "hunter22", "2012-06-01", "-", "trivial"),
    ("ShopSite", "zhou1985", "Zhou1985!shop", "2015-01-01", "2019-05-01",
     "trivial"),
    ("CloudDrive", "zhou@mail.com", "Sunny#day88", "2016-04-01", "-", "vital"),
    ("EmailMain", "zhou@mail.com", "Corr3ct-Horse!9", "2024-02-01",
     "2026-08-29", "vital"),
    ("BankApp", "zhou1985", "Tidy!Quilt7Lamp", "2023-11-01", "2026-08-30",
     "vital"),
    ("WorkLaptop", "zhou@corp.cn", "Ofn7!RoadQuiet", "2025-06-01",
     "2026-08-29", "vital"),
    ("StreamVideo", "zhou85@qq.com", "12345678", "2020-01-01", "2021-06-01",
     "trivial"),
    ("PizzaApp", "13800138000", "hunter22", "2022-05-01", "2022-08-01",
     "trivial"),
    ("NewsSite", "zhou@mail.com", "Sunny#day88", "2017-09-01", "2018-03-01",
     "normal"),
    ("GameStore", "zhou85@qq.com", "Dragon#Coast22", "2019-02-01",
     "2026-07-15", "normal"),
    ("UtilityBill", "zhou1985", "Tidy!Quilt7Lamp", "2018-08-01", "2025-08-01",
     "normal"),
]

MEI_ROWS = [
    ("Diary", "mei@post.com", "Ink&Well9go", "2025-04-01", "2026-08-01",
     "normal"),
    ("Bank", "mei@post.com", "Plumb!Dusk4Note", "2024-09-01", "2026-08-30",
     "vital"),
    ("Shop", "mei@post.com", "Amber-Vale8Hut", "2023-06-01", "2025-10-01",
     "trivial"),
]


def vault_files() -> dict:
    def render(rows) -> str:
        body = "\n".join("\t".join(r) for r in rows)
        return HEADER + body + "\n"
    return {
        "zhou-vault.tsv": render(ZHOU_ROWS),
        "mei-vault.tsv": render(MEI_ROWS),
    }


def sample_outputs() -> dict:
    """The four pinned outputs, produced by the real CLI code paths.
    Runs with CWD=examples so the pinned path in each sample is the bare
    file name — stable across machines."""
    out = {}
    cwd = os.getcwd()
    os.chdir(HERE)
    try:
        def capture(fn, *a):
            buf = io.StringIO()
            with redirect_stdout(buf):
                code = fn(*a)
            assert code == gl.EXIT_OK, (fn, code)
            return buf.getvalue()

        out["sample-report-zhou.txt"] = capture(
            gl.main, ["report", "zhou-vault.tsv"])
        out["sample-report-mei.txt"] = capture(
            gl.main, ["report", "mei-vault.tsv"])
        out["sample-clusters-zhou.txt"] = capture(
            gl.main, ["clusters", "zhou-vault.tsv"])
        out["sample-simulate-drop3.txt"] = capture(
            gl.main, ["simulate", "zhou-vault.tsv", "drop", "3"])
    finally:
        os.chdir(cwd)
    return out


def write_all(files: dict) -> None:
    for name, content in files.items():
        with open(os.path.join(HERE, name), "w", encoding="utf-8") as fh:
            fh.write(content)


def read_one(name: str) -> str:
    with open(os.path.join(HERE, name), "r", encoding="utf-8") as fh:
        return fh.read()


def check() -> int:
    bad = []
    vaults = vault_files()
    for name, content in sorted(vaults.items()):
        if read_one(name) != content:
            bad.append(name)
    if not bad:
        write_all(vaults)    # outputs read the vaults back from disk
        for name, content in sorted(sample_outputs().items()):
            if read_one(name) != content:
                bad.append(name)
    total = len(vaults) + len(sample_outputs())
    if bad:
        print("out of sync: %s" % ", ".join(bad))
        print("run: python3 examples/build_examples.py")
        return 1
    print("all %d example files in sync" % total)
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="verify committed files match a fresh rebuild")
    args = ap.parse_args()
    if args.check:
        return check()
    files = vault_files()
    write_all(files)         # vaults on disk first: outputs read them back
    files.update(sample_outputs())
    write_all(files)
    print("wrote %d files:" % len(files))
    for name in sorted(files):
        print("  %s" % name)
    return 0


if __name__ == "__main__":
    sys.exit(main())
